name: Update badges

on:
  schedule:
    # Runs at 2am UTC
    - cron: '32 0 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: francisco-cappelle/badge-readme@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CREDLY_USER: francisco-cappelle
          BADGE_SIZE: 85
          NUMBER_LAST_BADGES: 24
